### ISSUE TITLE
wrong results on pretrained GoogLeNet-HaS-32

### ISSUE THREAD

**Issue by RanTaimu** [kkanshul/Hide-and-Seek#1]
Hi, I'm a novice on Torch7. I'm sorry for my confusion about how to get the prediction of an image. I wrote the following code:

```lua
-- ....

local modelCache   = paths.concat('./cache', 'model_googlenet_has_32.t7')
local model = torch.load(modelCache) 
model:evaluate()
model:cuda()
-- print(model)

for line in io.lines(paths.concat(DATA_ROOT, '../images_1-25000.txt')) do
  line = split(line, " ")
  local img = testHook({loadSize}, paths.concat(DATA_ROOT, line[1]))

  if img:dim() == 3 then
    img = img:view(1, img:size(1), img:size(2), img:size(3))
  end

  local predictions = model:forward(img:cuda())
  local pred_idx, pred_sorted = predictions:sort(2, true)
  print(line[1])
  print(pred_sorted[1][1]-1)
end
```
Where 'testHook' is extracted from https://github.com/soumith/imagenet-multiGPU.torch. But I got hardly 0 top-1 accuracy on 'ILSVRC2012_img_val'. What's wrong with my code?

Looking forward to your reply :)

**Comment by kkanshul** [comment]
Hi RanTaimu,

I think you are not subtracting mean and dividing standard deviation from the image before feeding it to the network (meanstdCache.t7). Also, for the evaluation are using the order of the classes mentioned in the 'classes.t7'. Please let me know if I am not clear. Thanks!

**Comment by RanTaimu** [comment]
@kkanshul Yeah it's my fault ........ I didn't notice that the order of the classes. Thanks for your wonderful work!
