### ISSUE TITLE
Random cropping

### ISSUE THREAD

**Issue by lianxxx** [kkanshul/Hide-and-Seek#2]
What's the advantage of HaS over the random cropping that is commonly used for data augmentation?

**Comment by kkanshul** [comment]
Hi lianxxx,

With HaS, network sees partially hidden objects which makes it more robust to the occlusion and it is not possible through random crop (as you crop one big continuous region). Also HaS augment  images by hiding random patches which is different from random cropping data augmentation and can complement it (as shown in our paper). Finally, spatial alignment of the images are maintained by HaS.
