### ISSUE TITLE
setting the hidden pixel values

### ISSUE THREAD

**Issue by won-bae** [kkanshul/Hide-and-Seek#3]
Hi, Krishna

Thank you for sharing the source cod for the awesome paper!
I was reading your paper to embed HaS into my pytorch model.
You mentioned the hidden pixel values are supposed to set to the mean of all the pixel values in the entire training. Does that mean I just need to change 0 to the mean of all the pixels at line 30 in hide_patch.py? ( https://github.com/kkanshul/Hide-and-Seek/blob/5e77ed43b3208233a68681b37feb7de4dd6ecdb9/hide_patch.py#L30 )
Thank you in advance.

**Comment by kkanshul** [comment]
Hi Won-bae,

I was putting 0 assuming mean is already subtracted from the image (so the new mean is 0). So, if you have already subtracted the mean then keep it 0 otherwise put the mean value. Thanks!

**Comment by won-bae** [comment]
Thanks for your quick reply!

Sorry but does that mean I should not normalize by RGB channels that is conventionally employed, and instead just subtract the mean of the original pixel values? Or should I normalize by RGB channels as usual and then subtract the mean of the normalized pixel values?

**Comment by kkanshul** [comment]
You should normalize by RGB channels as usual but for hiding pixels set value to be 0. Let me know if you have any further doubts.

**Comment by won-bae** [comment]
Appreciate for the clarification!
